version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8000"
      - "8502:8501"
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3